### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [famask/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by famask** [comment]
I just added the following line to the head section of the application.html.erb file:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

Also pushed it to Heroku. Let me know if this is what was needed. Thanks.

**Comment by Mikeysax** [comment]
Nice job adding the mobile meta tag :+1:
